<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-SN0PPP1" failures="1" tests="5" name="Personal Loan" time="0.342" errors="0" timestamp="2021-01-15T12:26:13 IST">
  <testcase classname="test.Day4" name="APILoginCarLoan" time="0.011"/>
  <testcase classname="test.Day2" name="ploan" time="0.028"/>
  <testcase classname="test.Day4" name="MobileLoginCarLoan" time="0.009"/>
  <testcase classname="test.Day4" name="WebLoginCarLoan" time="0.004"/>
  <testcase classname="test.Day1" name="SecondTest" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.Day1.SecondTest(Day1.java:31)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- SecondTest -->
  <testcase classname="test.Day1" name="Demo" time="0.0">
    <ignored/>
  </testcase> <!-- Demo -->
</testsuite> <!-- Personal Loan -->
